# Generated by Django 4.2.4 on 2023-08-19 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="guardian",
        ),
        migrations.AddField(
            model_name="guardian",
            name="student",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="api.student"
            ),
            preserve_default=False,
        ),
    ]
