# Generated by Django 4.2.4 on 2023-09-20 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_student_guardian_guardian_student"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.room",
            ),
        ),
    ]
