# Generated by Django 4.2.4 on 2023-09-20 15:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_room_price_alter_student_room"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="staff",
            name="description",
        ),
    ]
