# Generated by Django 4.2.4 on 2023-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_staff_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
